config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :users
  resources :tracker_projects

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  

  validates :user, uniqueness: {scope: :project, message: "has already been added"}
  validates_presence_of :user

  belongs_to :project
  belongs_to :user

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :member_check
  before_action :owner_check

  def index
    @membership = @project.memberships.new
    @memberships = @project.memberships.all
  end

  def create
    membership_params = params.require(:membership).permit(
      :user_id, :role
    )
    @membership = @project.memberships.new(membership_params)
    if @membership.save
      redirect_to project_memberships_path(@project),
      notice: "#{@membership.user.full_name} was successfully added!"
    else
      render :index
    end
  end

  def update
    membership_params = params.require(:membership).permit(
      :user_id, :role
    )
    @membership = @project.memberships.find(params[:id])
    if owner_check || admin_check
      unless @project.memberships.where(role: "owner").count == 1
        if @membership.update(membership_params)
          redirect_to project_memberships_path(@project),
          notice: "#{@membership.user.full_name} was successfully updated!"
        else
          render :index
        end
      else
        render :index
      end
    end
  end

  def destroy
    @membership = @project.memberships.find(params[:id])
    if owner_check || current_user.id == @membership.user_id || admin_check
      @membership.destroy
      if owner_check || admin_check
        redirect_to project_memberships_path(@project),
        notice: "#{@membership.user.full_name} was successfully removed"
      else
        redirect_to projects_path,
        notice: "You were successfully removed"
      end
    end
  end

  private

  def member_check
    unless current_user.memberships.where(project_id: @project.id).exists? || current_user.admin
      raise AccessDenied
    end
  end

  def owner_check
    current_user.memberships.where(project_id: @project.id, role: "owner").exists?
  end


end

app/views/memberships/index.html.erb
<% if notice %>
<p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<div class="page-header">
  <h1><%= @project.name %>: Manage Members </h1>
</div>
<div class="row container">
  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Members</li>
  </ol>
</div>

<div class="row container">
<% if current_user.memberships.where(project_id: @project.id, role: "owner").exists? || admin_check %>
  <%= render "shared/errors", model: @membership %>
  <div class="well form-inline col-md-6 ">
    <%= form_for([@project, @membership], html: {class: "form-inline"}) do |f| %>
      <%= f.collection_select(:user_id, User.all, :id, :full_name,  {include_blank: "Please Select a User"}, {class: "form-control"}) %>
      <%= f.select :role, [:member, :owner], {}, {class: "form-control"} %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
</div>

<div class="row container">
  <table class="table-condensed">
    <% @project.users.each do |user| %>
      <% user.memberships.where(project_id: @project.id).each do |member| %>
        <tr>
        <%= form_for [@project, member], html: {class: "form-inline"} do |f|  %>
          <td><%=link_to user.full_name, user_path(user), class: "control-label " %></td>
          <% if current_user.memberships.where(project_id: @project.id, role: "owner").exists? || current_user.admin %>
            <td><%= f.select :role, [:member, :owner], {}, {class: "form-control"} %></td>
            <td><%= f.submit class: "btn btn-primary" %></td>
          <% end %>
          <% if current_user.memberships.where(project_id: @project.id, role: "owner").exists? ||
             member.user_id == current_user.id || current_user.admin %>
            <% if @project.memberships.where(role: "owner").count > 1 || member.role == "member" %>
              <td><%= link_to project_membership_path(@project, member), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-remove"></span></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>