config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :users
  resources :tracker_projects

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

end

app/models/task.rb
class Task < ActiveRecord::Base
  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
  validates :task, presence: true
  validate :not_past_date, on: :create

  belongs_to :project
  has_many :comments, dependent: :destroy

  def not_past_date
    if due_date
      if self.due_date < Date.today
        errors.add(:due_date, 'cannot be in the past')
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  @new_task = true

  # GET /tasks
  # GET /tasks.json
  def index

    if params[:sort_by] == "all"
      @tasks = @project.tasks.all
    else
      @tasks = @project.tasks.where(complete: false)
    end
    @task_csv = @project.tasks.order(:created_at)

    respond_to do |format|
      format.html
      format.csv { send_data @task_csv.as_csv }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = @project.tasks.find(params[:id])
    @comment = @task.comments.new
    @comments = @task.comments.all
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new

  end

  # GET /tasks/1/edit
  def edit
    authorize_member unless owner_check
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)
    if member_check || admin_check
      respond_to do |format|
        if @task.save
          format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.' }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if member_check || admin_check
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.' }
          format.json { render :show, status: :ok, location: @task }
        else
          format.html { render :edit }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if member_check || admin_check
      @task.destroy
      respond_to do |format|
        format.html { redirect_to project_tasks_url(@project), notice: 'Task was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def member_check
    current_user.memberships.where(project_id: @project.id).exists?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task, :due_date, :complete)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task], html: {class: "form-horizontal"}) do |f| %>

    <div class="col-sm-6 row">
      <div class="field form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <%= render 'shared/errors', model: @task  %>
        </div>
      </div>

    <div class="field form-group">
      <%= f.label :task, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :task, :class => "form-control"%>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :due_date, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.date_field :due_date, :class => "col-sm-10 form-control" %>
      </div>
    </div>
    <% if @task.id %>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-11">
          <div class="checkbox">
            <label>
              <%= f.check_box :complete  %> Complete
            </label>
          </div>
        </div>
      </div>
  <% else %>
    <% @task.complete = false %>
  <%end%>

  <div class="actions field form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
  </div>
  <br>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>
<br>

<%= render 'form' %>

app/views/tasks/index.html.erb
<% if notice != nil %>
  <p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<div class="page-header">
  <div class="pull-right">
    <%= link_to_unless_current 'All', project_tasks_path(sort_by: "all")  %> |
    <%if params[:sort_by] == nil%>
      Incomplete
    <%else%>
      <%= link_to 'Incomplete', project_tasks_path %>
    <%end%>
    <% if current_user.memberships.where(project_id: @project.id).exists? || admin_check %>
      <%= link_to 'Create Task', new_project_task_path, class: "btn btn-info" %>
    <% end %>
  </div>
  <h1>Tasks</h1>
</div>

  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Tasks</li>
  </ol>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Due Date</th>
      <th>Complete?</th>

      <th colspan="2"></th>

    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.due_date  %>
        <% due_week = (task.due_date - Date.today) %>

        <% if due_week <=7 %>
          <tr class="alert alert-warning">
        <% else %>
          <tr>
        <% end %>

      <% else %>
          <tr>
      <% end %>

      <td class="col-md-6"><%= link_to task.task, project_task_path(@project, task) %>
         <span class="badge"><%= task.comments.count %></span></td>
      <% if task.due_date == nil %>
        <td class="col-md-2"> none </td>
      <%else%>
        <td class="col-md-2"><%= task.due_date.strftime("%B %e %Y") %></td>
      <%end%>
      <%if task.complete == true%>
        <td class="col-md-1">Complete</td>
      <%else%>
        <td class="col-md-1">Incomplete</td>
      <%end%>
      <td class="col-md-3">
        <% if current_user.memberships.where(project_id: @project.id).exists? %>
        <div class="pull-right">
        <%= link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-warning btn-sm" %>
        <%= link_to project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %></td>
      </div>
        <% end %>
    </tr>
  <% end %>

  </tbody>
</table>
<%= link_to "Download CSV", project_tasks_path(format: "csv") %>

<br>

app/views/tasks/new.html.erb
<h1>New task</h1>
<br>

<%= render 'form' %>

app/views/tasks/show.html.erb
<% if notice != nil %>
  <p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_task_path(@project, @task), class: "btn btn-primary"%>
  </div>
  <h1><%= @task.task %></h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path %></li>
  <li class="active">Show</li>
</ol>

<p>
  <strong>Due Date:</strong>
  <% if @task.due_date %>
    <%= @task.due_date.strftime("%B %e, %Y") %>
  <% else %>
    None
  <% end %>
</p>
<p>
  <strong>Complete?</strong>
  <%= @task.complete %>
</p>

<br>
<table class="table">
  <tbody>
    <% @task.comments.where(:created_at != nil).each do |comment| %>
        <tr>
          <td class="col-md-3">
          <% if comment.user == nil  %>
            <span class="text-muted">Deleted User</span>
          <% else %>
            <%= link_to comment.user.full_name, user_path(comment.user_id) %>
          <% end %>
            <br><span class="text-muted"><%= time_ago_in_words(comment.created_at) %> ago</span>
            </td>
          <td class="col-md-9"><%= comment.description %></td>
        </tr>
    <% end %>
  </tbody>
</table>



  <% if current_user %>
    <%= form_for [@project, @task, @comment], html: {class: "form-horizontal"} do |f| %>

      <div class="form-group">
        <div class=" col-sm-9 col-sm-offset-3">
          <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>

      <div class="actions form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <%= f.submit class: " btn btn-primary" %>
        </div>
      </div>

    <% end %>
  <% end %>