config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :users
  resources :tracker_projects

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :not_logged_in
  before_action :set_project, only: [:edit, :update, :destroy, :show]
  before_action :authorize_owner, only: [:edit, :update, :destroy]

  helper_method :owner_check

  def index
    @projects = Project.all
    tracker_api = TrackerAPI.new
    @tracker_projects = tracker_api.projects(current_user.tracker_token)
  end

  def new
    @project = Project.new
    @new_project = true
  end

  def create
    project_params = params.require(:project).permit(:name)
    @project = Project.new(project_params)
    @owner = @project.memberships.new(
      project_id: @project.id,
      user_id: current_user.id,
      role: "owner")
    if @project.save
      @owner.save
      flash[:notice] = "Project was successfully created"
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def show
    authorize_member unless admin_check
  end

  def edit
    @project = Project.find(params[:id])

    @edit_project = true
  end

  def update
    if owner_check || admin_check
      project_params = params.require(:project).permit(:name)
      if @project.update(project_params)
        flash[:notice] = "Project was successfully updated"
        redirect_to project_path(@project)
      else
        render :edit
      end
    end
  end

  def destroy
    if owner_check || admin_check
      @project.destroy
      flash[:notice] = "Project was successfully destroyed"
      redirect_to projects_path
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end



end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>

  <div class="col-sm-6 row">
    <div class="field form-group">
      <div class="col-sm-offset-3 col-sm-9">
        <%= render 'shared/errors', model: @project  %>
      </div>
    </div>


      <div class="field form-group">
          <%= f.label :name, class: "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="actions field form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
      <br>

  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Editing Project</h1>
</div>


<%= render 'form' %>

app/views/projects/index.html.erb
<% if notice != nil %>
  <p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<%= page_header "Projects" do %>
  <%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
<% end %>



<table class="table">
  <thead>
    <th>Project</th>
    <th>Members</th>
    <th>Tasks</th>
  </thead>
  <tbody>
    <% if current_user.admin == true %>
      <% @projects.each do |project| %>
        <tr>
          <td class="col-md-4"><%= link_to project.name, project_path(project) %></td>
          <td><%= link_to project.memberships.count, project_memberships_path(project) %></td>
          <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
        </tr>
      <% end %>
    <% else %>
      <% current_user.projects.each do |project| %>
        <tr>
          <td class="col-md-4"><%= link_to project.name, project_path(project) %></td>
          <td><%= link_to project.memberships.count, project_memberships_path(project) %></td>
          <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<% if current_user.tracker_token %>
  <div class="page-header">
    <h1>Pivotal Tracker Projects</h1>
  </div>

  <table class="table">
    <thead>
      <th>Name</th>
    </thead>
    <tbody>
    <% @tracker_projects.each do |tracker_project| %>
      <tr>
        <td>
          <%= link_to tracker_project[:name], tracker_project_path(tracker_project[:id]) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


  <hr>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>


<%= render 'form' %>

app/views/projects/show.html.erb
<% if notice != nil %>
  <p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>

<div class="page-header">
  <% if current_user.memberships.where(project_id: @project.id, role: "owner").exists? || admin_check %>
  <div class="pull-right">
    <%= link_to "Edit", edit_project_path(@project), class: "btn btn-warning" %>
  </div>
  <% end %>
  <h1><%= @project.name %></h1>
</div>
  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li class="active">Show</li>
  </ol>

  <p>
  <%= link_to pluralize(@project.tasks.count, "Task"), project_tasks_path(@project) %>
  </p>
  <p>
  <%= link_to pluralize(@project.users.count, "Member"), project_memberships_path(@project) %>
  </p>
  <% if current_user.memberships.where(project_id: @project.id, role: "owner").exists? || current_user.admin %>
  <div class="well">
    <p>
      <strong>Delete Project</strong>
    </p>
    <p>
      Deleting this project with also delete <%= pluralize(@project.memberships.count, "membership") %>,
      <%= pluralize(@project.tasks.count, "task") %>, and associated comments.
    </p>
    <%= link_to "Delete", project_path(@project), class: "btn btn-danger",
      :method => :delete, data: {confirm: "Are you sure?"} %>

  </div>
  <% end %>

<br>
<br>
<%= link_to "back", projects_path, class: "btn btn-primary" %>