config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :users
  resources :tracker_projects

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="vie wport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= content_for(:title) || "gCamp" %></title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>w
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <ul class="nav navbar-nav navbar_right pull-right">
            <% if current_user %>
              <li><%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path("#{current_user.id}") %></li>
              <li><%= link_to "Sign Out", signout_path, class: "ul nav" %></li>
            <% else %>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Sign In", signin_path %></li>
            <% end %>
          </ul>
          <div class="navbar-header">

            <div class="home_button">
              <%= link_to "gCamp", projects_path, class: "navbar-brand" %>
            </div>
          </div>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                My Projects
                <span class="caret"></span>

              <ul class="dropdown-menu" role="menu">

                <% current_user.memberships.where(role: "owner").each do |membership| %>
                  <li><%= link_to membership.project.name, project_path(membership.project) %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "New Project", new_project_path %></li>
              </ul>
            </li>
            <li><%= link_to "Users", users_path%></li>
          </ul>

          <div class="nav navbar-nav">

          </div>

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

          <div class="navbar-collapse collapse">
          </div><!--/.navbar-collapse -->
        </div>
      </div>

<div class="container">

<%= yield %>

</div> <!-- /container -->


<hr>
<div class="container">

<footer>

  <div class="text-center">
    <p>
    <%= link_to_unless_current "Home", root_path %> |
    <%= link_to_unless_current "About", about_path %> |
    <%= link_to_unless_current "Terms", terms_path %> |
    <%= link_to_unless_current "FAQ", faq_path %>
  </p>
  </div>

</footer>

</div>


</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gCamp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="vie wport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>w
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <ul class="nav navbar-nav navbar_right pull-right">
            <% if current_user %>
              <li><%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path("#{current_user.id}") %></li>
              <li><%= link_to "Sign Out", signout_path, class: "ul nav" %></li>
            <% else %>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Sign In", signin_path %></li>
            <% end %>
          </ul>
          <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <div class="home_button">
              <%= link_to "gCamp", root_path, class: "navbar-brand" %>
            </div>

          </div>
          <div class="navbar-collapse collapse">
          </div><!--/.navbar-collapse -->
        </div>
      </div>

<div class="container">

<%= yield %>

</div> <!-- /container -->


<hr>
<div class="container">

<footer>
  <p>&copy; Mello Incorporated 2014</p>
  <div class="pull-right">
    <%= link_to "https://www.linkedin.com/in/mellodan" do %>
      <%= image_tag("linked_in.png", width: "20em")%>
    <% end %> |
    <%= link_to "https://github.com/mfvico" do %>
      <%= image_tag("GitHub-Mark.png", width: "20em")%>
    <% end %> |
    <%= link_to "https://twitter.com/vicomello" do %>
      <%= image_tag("Twitter_logo.png", width: "20em")%>
    <% end %> |
    <%= link_to "http://students.gschool.it" do %>
      <%= image_tag("Galvanize-g.png", width: "20em")%>
    <% end %>
  </div>
  <div>
    <p><%= link_to_unless_current "About", about_path %> |
    <%= link_to_unless_current "Terms", terms_path %> |
    <%= link_to_unless_current "FAQ", faq_path %>
    <% if current_user %>
      | <%= link_to_unless_current "My Projects", projects_path %>
    <% end %>

  </p>
  </div>

</footer>

</div>


</body>
</html>